server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-db:5432/userdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: mySecretKeyForJWTTokenGeneration2024EcommercePlatform
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
